version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: vikyath
      POSTGRES_PASSWORD: komatireddy
      POSTGRES_DB: hfdatasets
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vikyath"]
      interval: 5s
      retries: 5

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.example
    ports:
      - "8000:80"
    volumes:
      - ./:/app          # live-reload while editing (dev)

volumes:
  db_data:
